# Generated by Django 3.0.7 on 2020-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Test Description', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.URLField(default=''),
        ),
    ]
